# Generated by Django 4.2.18 on 2025-02-05 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_tollstation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(help_text='Enter the car color', max_length=50)),
                ('length', models.FloatField(verbose_name='car`s length')),
                ('load_volume', models.FloatField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='car.owner')),
            ],
        ),
    ]
