# Generated by Django 4.2.18 on 2025-02-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_car_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='load_volume',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
