# Generated by Django 4.2.18 on 2025-02-07 08:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_alter_car_load_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='total_toll_paid',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Positioning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='car.car')),
            ],
        ),
    ]
