# Generated by Django 4.2.18 on 2025-02-07 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_owner_total_toll_paid_positioning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='total_toll_paid',
        ),
    ]
