# Generated by Django 4.2.18 on 2025-02-07 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_remove_owner_total_toll_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarToll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('toll', models.PositiveIntegerField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tolls', to='car.car')),
            ],
        ),
    ]
